### ISSUE TITLE
Bug: French is failing schema validation due to missing values

### ISSUE THREAD

**Issue by DaveOrDead** [kinde-oss/kinde-translations#32]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Several keys missing from French translation file

### Library URL

https://github.com/kinde-oss/kinde-translations

### Library version

1

### Operating system(s)

macOS

### Operating system version(s)

N/A

**Comment by umuthopeyildirim** [comment]
How about tagging it with #good-first-issue or #help-wanted to grab some eyes?
