### ISSUE TITLE
Feature request: PR validator should only run against changed files

### ISSUE THREAD

**Issue by DaveOrDead** [kinde-oss/kinde-translations#36]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

It's inevitable that some files will fall behind as new features are introduced to the app. 

At the moment French is lagging behind which is causing all PRs to look like they are failing. We need to update the validator that runs on GH to just run against changed files / those affected by the PR.

It is still worth keeping the check that runs against all files in the codebase for local checking, so adding another script would be awesome

### What solution would you like to see?

An additional script that runs validation against changed files only in the GH action

**Comment by umuthopeyildirim** [comment]
Hi @DaveOrDead,

I've just pushed some updates in PR #40. When you have a moment, could you take a look? So I can fix any problems with it.

Thanks!
