### ISSUE TITLE
Feature request: Support for Korean?

### ISSUE THREAD

**Issue by MediGenie** [kinde-oss/kinde-translations#65]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

Can you support Korean for sign in or login? I would be down to translate on your behalf.

### What solution would you like to see?

Can you support Korean for sign in or login? I would be down to translate on your behalf.

**Comment by DanielRivers** [comment]
Hey @MediGenie!

If you're happy to help with the translation, please do follow the readme we would happily include.

**Comment by DaveOrDead** [comment]
closing as PR merged last month
