### ISSUE TITLE
Feature request: name order

### ISSUE THREAD

**Issue by passatgt** [kinde-oss/kinde-translations#69]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

Hi! I'm working on the Hungarian translation. In Hungary we use the easter name order, so family name(last name) comes first, and then given name(first name). Source: https://en.wikipedia.org/wiki/Personal_name#Eastern_name_order

Would be nice to support this, because it affects other languages too, for example Japanese. 

### What solution would you like to see?

Respect the name order based on the language. If there was a way to add custom CSS to the signup page, i could flip the fields using CSS, but this is not ideal due to accessibility reasons(pressing tab goes to wrong field). So ideally it would actually flip the fields in source on language change. 

### Additional information

Tricky, i know.. sorry

**Comment by passatgt** [comment]
Hi! @DanielRivers!

As far as i know only Hungarian and Japanese. At least in WooCommerce, only these two countries are handled, here is an example: 
https://github.com/woocommerce/woocommerce/blob/d6a48ecaf5f24d76b9aaaad3f2d1d50ade5ea159/plugins/woocommerce/includes/class-wc-countries.php#L584
You can see that only HU and JP has the name order changed, the rest are using the standard order.

I can't speak about Japanese, but in Hungary, it's not subjective, this is how we use our names here. Maybe if the UI is english, you might keep the western order.

**Comment by DanielRivers** [comment]
Thanks for this @passatgt, 

I discussed this internally today with the team.  Will look into this.

**Comment by DaveOrDead** [comment]
Hey @passatgt this feature is now implemented - let me know if it is working for you :) 

Thanks for the awesome suggestion 🚀

**Comment by passatgt** [comment]
Hi! Sorry about opening this up again, but theres one minor issue with this. Auto-focus :) So when the fields are reversed, the second field(first name) will be focused on page load instead of the first field :)

**Comment by DanielRivers** [comment]
Hi @passatgt, oh no, sorry about this, we will get this fixed up for you.

**Comment by DanielRivers** [comment]
@passatgt You will be pleased to hear a PR has just been opened to resolve this.  Its just going through some reviews but as its a small change I can't see it taking too long.

**Comment by DaveOrDead** [comment]
Hey @passatgt should be working as expected now - are you able to confirm?

**Comment by passatgt** [comment]
Hi @DaveOrDead, thanks for the quick fix. It does work on the signup page, but not on the request access page :)

**Comment by DaveOrDead** [comment]
Hey @passatgt took me a minute to get back to this - but should now be fixed there also
